name: "Madusudanan.B.N"
description: "Personal website of Madusudanan.B.N"
author: "Madusudanan.B.N"

# url: "http://localhost:4000"
url: "http://madusudanan.com"

exclude: [Rakefile]
comments: true
permalink: /blog/:title

gems:
  - jekyll-sitemap
  - jekyll-feed
