name: "Samurai Coder"
description: "Home of the Samurai Coder"
author: "Madusudanan.B.N"

# url: "http://localhost:4000"
url: "http://samuraicoder.in"

exclude: [Rakefile]
comments: true
permalink: /blog/:title

